### ISSUE TITLE
Feature request: World specification

### ISSUE THREAD

**Issue by SlimeDog** [Block2Block/HubParkour-Legacy#2]
Please implement configuration option to specify worlds that contains parkour, and limit parkour to only those worlds. Use case: I run multiworld servers, where the parkour is not world "world" but world "world_parkour" (and the hub is world "world_lobby"). I want HubParkour to be applied only in world_parkour.

**Comment by Block2Block** [comment]
Hi!

Because of the way parkour is handled, this works as you expected anyway. The parkour pressure plates will only work in the world in which you set them up and it will not pick up pressure plates not registered with the plugin, as the Bukkit API automatically stores this as a part of the object I use to handle location tracking.

Are you referring to only having commands work in a specific world?

**Comment by SlimeDog** [comment]
OK, that's great. I will give it a go.

WRT commands working only in the specified world, I can manage that with permissions.

Thanks.
